/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Shift = IDL.Record({
  'id' : IDL.Text,
  'endHour' : IDL.Nat,
  'name' : IDL.Text,
  'gracePeriodMinutes' : IDL.Nat,
  'endMinute' : IDL.Nat,
  'halfDayHours' : IDL.Float64,
  'startMinute' : IDL.Nat,
  'startHour' : IDL.Nat,
});
export const LeaveStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const LeaveType = IDL.Variant({
  'paid' : IDL.Null,
  'sick' : IDL.Null,
  'unpaid' : IDL.Null,
  'casual' : IDL.Null,
});
export const LeaveRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : LeaveStatus,
  'appliedAt' : IDL.Int,
  'endDate' : IDL.Text,
  'days' : IDL.Float64,
  'reviewNote' : IDL.Opt(IDL.Text),
  'reviewedAt' : IDL.Opt(IDL.Int),
  'reviewedBy' : IDL.Opt(IDL.Text),
  'employeeId' : IDL.Text,
  'leaveType' : LeaveType,
  'startDate' : IDL.Text,
  'reason' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Branch = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'location' : IDL.Text,
});
export const EmployeeKey = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Employee = IDL.Record({
  'id' : EmployeeKey,
  'salary' : IDL.Float64,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'role' : IDL.Text,
  'joiningDate' : IDL.Text,
  'isActive' : IDL.Bool,
  'email' : IDL.Text,
  'employeeId' : IDL.Text,
  'phone' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'department' : IDL.Text,
  'branchId' : IDL.Text,
  'shiftId' : IDL.Text,
});
export const Holiday = IDL.Record({
  'id' : IDL.Text,
  'holidayType' : IDL.Text,
  'isRecurring' : IDL.Bool,
  'date' : IDL.Text,
  'name' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const LeaveBalance = IDL.Record({
  'paid' : IDL.Float64,
  'sick' : IDL.Float64,
  'year' : IDL.Int,
  'unpaid' : IDL.Float64,
  'employeeId' : IDL.Text,
  'casual' : IDL.Float64,
});
export const AttendanceStatus = IDL.Variant({
  'halfDay' : IDL.Null,
  'present' : IDL.Null,
  'late' : IDL.Null,
  'absent' : IDL.Null,
  'holiday' : IDL.Null,
});
export const AttendanceRecord = IDL.Record({
  'id' : IDL.Text,
  'locationLat' : IDL.Opt(IDL.Float64),
  'locationLng' : IDL.Opt(IDL.Float64),
  'status' : AttendanceStatus,
  'date' : IDL.Text,
  'checkInTime' : IDL.Opt(IDL.Int),
  'employeeId' : IDL.Text,
  'notes' : IDL.Text,
  'checkOutTime' : IDL.Opt(IDL.Int),
  'overtimeMinutes' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'leaveApproved' : IDL.Null,
  'leaveRejected' : IDL.Null,
  'lateAlert' : IDL.Null,
  'general' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'userId' : IDL.Principal,
  'notificationType' : NotificationType,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'relatedId' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addShift' : IDL.Func([Shift], [], []),
  'applyLeave' : IDL.Func([LeaveRequest], [IDL.Text], []),
  'approveLeave' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkIn' : IDL.Func(
      [IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64), IDL.Text],
      [IDL.Text],
      [],
    ),
  'checkOut' : IDL.Func([IDL.Text], [], []),
  'createBranch' : IDL.Func([Branch], [], []),
  'createEmployee' : IDL.Func([Employee], [], []),
  'createHoliday' : IDL.Func([Holiday], [], []),
  'deleteEmployee' : IDL.Func([EmployeeKey], [], []),
  'deleteHoliday' : IDL.Func([IDL.Text], [], []),
  'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
  'getBranch' : IDL.Func([IDL.Text], [Branch], ['query']),
  'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalWorkingHoursThisMonth' : IDL.Float64,
          'totalEmployees' : IDL.Nat,
          'presentToday' : IDL.Nat,
          'lateToday' : IDL.Nat,
          'pendingLeaves' : IDL.Nat,
          'absentToday' : IDL.Nat,
          'avgWorkingHoursPerEmployee' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getEmployee' : IDL.Func([EmployeeKey], [Employee], ['query']),
  'getHoliday' : IDL.Func([IDL.Text], [Holiday], ['query']),
  'getHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
  'getLeaveBalance' : IDL.Func([IDL.Text], [IDL.Opt(LeaveBalance)], ['query']),
  'getMyAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getMyLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(Employee)], ['query']),
  'getPayrollSummary' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Int],
      [
        IDL.Record({
          'salary' : IDL.Float64,
          'estimatedEarnings' : IDL.Float64,
          'daysPresent' : IDL.Nat,
          'workingDays' : IDL.Nat,
          'overtimeHours' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getPendingLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
  'getShift' : IDL.Func([IDL.Text], [Shift], ['query']),
  'getShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
  'getTeamAttendance' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getTodayStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'present' : IDL.Nat,
          'late' : IDL.Nat,
          'absent' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initLeaveBalance' : IDL.Func([LeaveBalance], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAbsent' : IDL.Func([IDL.Text], [], []),
  'markAllRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Text], [], []),
  'rejectLeave' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchEmployees' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Employee)],
      ['query'],
    ),
  'updateBranch' : IDL.Func([IDL.Text, Branch], [], []),
  'updateEmployee' : IDL.Func([EmployeeKey, Employee], [], []),
  'updateShift' : IDL.Func([IDL.Text, Shift], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Shift = IDL.Record({
    'id' : IDL.Text,
    'endHour' : IDL.Nat,
    'name' : IDL.Text,
    'gracePeriodMinutes' : IDL.Nat,
    'endMinute' : IDL.Nat,
    'halfDayHours' : IDL.Float64,
    'startMinute' : IDL.Nat,
    'startHour' : IDL.Nat,
  });
  const LeaveStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const LeaveType = IDL.Variant({
    'paid' : IDL.Null,
    'sick' : IDL.Null,
    'unpaid' : IDL.Null,
    'casual' : IDL.Null,
  });
  const LeaveRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : LeaveStatus,
    'appliedAt' : IDL.Int,
    'endDate' : IDL.Text,
    'days' : IDL.Float64,
    'reviewNote' : IDL.Opt(IDL.Text),
    'reviewedAt' : IDL.Opt(IDL.Int),
    'reviewedBy' : IDL.Opt(IDL.Text),
    'employeeId' : IDL.Text,
    'leaveType' : LeaveType,
    'startDate' : IDL.Text,
    'reason' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Branch = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'location' : IDL.Text,
  });
  const EmployeeKey = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Employee = IDL.Record({
    'id' : EmployeeKey,
    'salary' : IDL.Float64,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'role' : IDL.Text,
    'joiningDate' : IDL.Text,
    'isActive' : IDL.Bool,
    'email' : IDL.Text,
    'employeeId' : IDL.Text,
    'phone' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'department' : IDL.Text,
    'branchId' : IDL.Text,
    'shiftId' : IDL.Text,
  });
  const Holiday = IDL.Record({
    'id' : IDL.Text,
    'holidayType' : IDL.Text,
    'isRecurring' : IDL.Bool,
    'date' : IDL.Text,
    'name' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const LeaveBalance = IDL.Record({
    'paid' : IDL.Float64,
    'sick' : IDL.Float64,
    'year' : IDL.Int,
    'unpaid' : IDL.Float64,
    'employeeId' : IDL.Text,
    'casual' : IDL.Float64,
  });
  const AttendanceStatus = IDL.Variant({
    'halfDay' : IDL.Null,
    'present' : IDL.Null,
    'late' : IDL.Null,
    'absent' : IDL.Null,
    'holiday' : IDL.Null,
  });
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Text,
    'locationLat' : IDL.Opt(IDL.Float64),
    'locationLng' : IDL.Opt(IDL.Float64),
    'status' : AttendanceStatus,
    'date' : IDL.Text,
    'checkInTime' : IDL.Opt(IDL.Int),
    'employeeId' : IDL.Text,
    'notes' : IDL.Text,
    'checkOutTime' : IDL.Opt(IDL.Int),
    'overtimeMinutes' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'leaveApproved' : IDL.Null,
    'leaveRejected' : IDL.Null,
    'lateAlert' : IDL.Null,
    'general' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'userId' : IDL.Principal,
    'notificationType' : NotificationType,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'relatedId' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addShift' : IDL.Func([Shift], [], []),
    'applyLeave' : IDL.Func([LeaveRequest], [IDL.Text], []),
    'approveLeave' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkIn' : IDL.Func(
        [IDL.Opt(IDL.Float64), IDL.Opt(IDL.Float64), IDL.Text],
        [IDL.Text],
        [],
      ),
    'checkOut' : IDL.Func([IDL.Text], [], []),
    'createBranch' : IDL.Func([Branch], [], []),
    'createEmployee' : IDL.Func([Employee], [], []),
    'createHoliday' : IDL.Func([Holiday], [], []),
    'deleteEmployee' : IDL.Func([EmployeeKey], [], []),
    'deleteHoliday' : IDL.Func([IDL.Text], [], []),
    'getAllEmployees' : IDL.Func([], [IDL.Vec(Employee)], ['query']),
    'getBranch' : IDL.Func([IDL.Text], [Branch], ['query']),
    'getBranches' : IDL.Func([], [IDL.Vec(Branch)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalWorkingHoursThisMonth' : IDL.Float64,
            'totalEmployees' : IDL.Nat,
            'presentToday' : IDL.Nat,
            'lateToday' : IDL.Nat,
            'pendingLeaves' : IDL.Nat,
            'absentToday' : IDL.Nat,
            'avgWorkingHoursPerEmployee' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getEmployee' : IDL.Func([EmployeeKey], [Employee], ['query']),
    'getHoliday' : IDL.Func([IDL.Text], [Holiday], ['query']),
    'getHolidays' : IDL.Func([], [IDL.Vec(Holiday)], ['query']),
    'getLeaveBalance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LeaveBalance)],
        ['query'],
      ),
    'getMyAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getMyLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(Employee)], ['query']),
    'getPayrollSummary' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Int],
        [
          IDL.Record({
            'salary' : IDL.Float64,
            'estimatedEarnings' : IDL.Float64,
            'daysPresent' : IDL.Nat,
            'workingDays' : IDL.Nat,
            'overtimeHours' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getPendingLeaves' : IDL.Func([], [IDL.Vec(LeaveRequest)], ['query']),
    'getShift' : IDL.Func([IDL.Text], [Shift], ['query']),
    'getShifts' : IDL.Func([], [IDL.Vec(Shift)], ['query']),
    'getTeamAttendance' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getTodayStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'present' : IDL.Nat,
            'late' : IDL.Nat,
            'absent' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getUnreadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initLeaveBalance' : IDL.Func([LeaveBalance], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAbsent' : IDL.Func([IDL.Text], [], []),
    'markAllRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Text], [], []),
    'rejectLeave' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchEmployees' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Employee)],
        ['query'],
      ),
    'updateBranch' : IDL.Func([IDL.Text, Branch], [], []),
    'updateEmployee' : IDL.Func([EmployeeKey, Employee], [], []),
    'updateShift' : IDL.Func([IDL.Text, Shift], [], []),
  });
};

export const init = ({ IDL }) => { return []; };