/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'id' : string,
  'locationLat' : [] | [number],
  'locationLng' : [] | [number],
  'status' : AttendanceStatus,
  'date' : string,
  'checkInTime' : [] | [bigint],
  'employeeId' : string,
  'notes' : string,
  'checkOutTime' : [] | [bigint],
  'overtimeMinutes' : bigint,
}
export type AttendanceStatus = { 'halfDay' : null } |
  { 'present' : null } |
  { 'late' : null } |
  { 'absent' : null } |
  { 'holiday' : null };
export interface Branch {
  'id' : string,
  'name' : string,
  'isActive' : boolean,
  'location' : string,
}
export interface Employee {
  'id' : EmployeeKey,
  'salary' : number,
  'userId' : Principal,
  'name' : string,
  'designation' : string,
  'role' : string,
  'joiningDate' : string,
  'isActive' : boolean,
  'email' : string,
  'employeeId' : string,
  'phone' : string,
  'photo' : [] | [ExternalBlob],
  'department' : string,
  'branchId' : string,
  'shiftId' : string,
}
export type EmployeeKey = string;
export type ExternalBlob = Uint8Array;
export interface Holiday {
  'id' : string,
  'holidayType' : string,
  'isRecurring' : boolean,
  'date' : string,
  'name' : string,
}
export interface LeaveBalance {
  'paid' : number,
  'sick' : number,
  'year' : bigint,
  'unpaid' : number,
  'employeeId' : string,
  'casual' : number,
}
export interface LeaveRequest {
  'id' : string,
  'status' : LeaveStatus,
  'appliedAt' : bigint,
  'endDate' : string,
  'days' : number,
  'reviewNote' : [] | [string],
  'reviewedAt' : [] | [bigint],
  'reviewedBy' : [] | [string],
  'employeeId' : string,
  'leaveType' : LeaveType,
  'startDate' : string,
  'reason' : string,
}
export type LeaveStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type LeaveType = { 'paid' : null } |
  { 'sick' : null } |
  { 'unpaid' : null } |
  { 'casual' : null };
export interface Notification {
  'id' : string,
  'title' : string,
  'userId' : Principal,
  'notificationType' : NotificationType,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'relatedId' : [] | [string],
}
export type NotificationType = { 'leaveApproved' : null } |
  { 'leaveRejected' : null } |
  { 'lateAlert' : null } |
  { 'general' : null };
export interface Shift {
  'id' : string,
  'endHour' : bigint,
  'name' : string,
  'gracePeriodMinutes' : bigint,
  'endMinute' : bigint,
  'halfDayHours' : number,
  'startMinute' : bigint,
  'startHour' : bigint,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addShift' : ActorMethod<[Shift], undefined>,
  'applyLeave' : ActorMethod<[LeaveRequest], string>,
  'approveLeave' : ActorMethod<[string, [] | [string]], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkIn' : ActorMethod<[[] | [number], [] | [number], string], string>,
  'checkOut' : ActorMethod<[string], undefined>,
  'createBranch' : ActorMethod<[Branch], undefined>,
  'createEmployee' : ActorMethod<[Employee], undefined>,
  'createHoliday' : ActorMethod<[Holiday], undefined>,
  'deleteEmployee' : ActorMethod<[EmployeeKey], undefined>,
  'deleteHoliday' : ActorMethod<[string], undefined>,
  'getAllEmployees' : ActorMethod<[], Array<Employee>>,
  'getBranch' : ActorMethod<[string], Branch>,
  'getBranches' : ActorMethod<[], Array<Branch>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalWorkingHoursThisMonth' : number,
      'totalEmployees' : bigint,
      'presentToday' : bigint,
      'lateToday' : bigint,
      'pendingLeaves' : bigint,
      'absentToday' : bigint,
      'avgWorkingHoursPerEmployee' : number,
    }
  >,
  'getEmployee' : ActorMethod<[EmployeeKey], Employee>,
  'getHoliday' : ActorMethod<[string], Holiday>,
  'getHolidays' : ActorMethod<[], Array<Holiday>>,
  'getLeaveBalance' : ActorMethod<[string], [] | [LeaveBalance]>,
  'getMyAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getMyLeaves' : ActorMethod<[], Array<LeaveRequest>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyProfile' : ActorMethod<[], [] | [Employee]>,
  'getPayrollSummary' : ActorMethod<
    [string, string, bigint],
    {
      'salary' : number,
      'estimatedEarnings' : number,
      'daysPresent' : bigint,
      'workingDays' : bigint,
      'overtimeHours' : number,
    }
  >,
  'getPendingLeaves' : ActorMethod<[], Array<LeaveRequest>>,
  'getShift' : ActorMethod<[string], Shift>,
  'getShifts' : ActorMethod<[], Array<Shift>>,
  'getTeamAttendance' : ActorMethod<[string], Array<AttendanceRecord>>,
  'getTodayStats' : ActorMethod<
    [],
    { 'present' : bigint, 'late' : bigint, 'absent' : bigint }
  >,
  'getUnreadCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initLeaveBalance' : ActorMethod<[LeaveBalance], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAbsent' : ActorMethod<[string], undefined>,
  'markAllRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[string], undefined>,
  'rejectLeave' : ActorMethod<[string, [] | [string]], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchEmployees' : ActorMethod<[string, string], Array<Employee>>,
  'updateBranch' : ActorMethod<[string, Branch], undefined>,
  'updateEmployee' : ActorMethod<[EmployeeKey, Employee], undefined>,
  'updateShift' : ActorMethod<[string, Shift], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];