/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Shift {
    id: string;
    endHour: bigint;
    name: string;
    gracePeriodMinutes: bigint;
    endMinute: bigint;
    halfDayHours: number;
    startMinute: bigint;
    startHour: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface LeaveRequest {
    id: string;
    status: LeaveStatus;
    appliedAt: bigint;
    endDate: string;
    days: number;
    reviewNote?: string;
    reviewedAt?: bigint;
    reviewedBy?: string;
    employeeId: string;
    leaveType: LeaveType;
    startDate: string;
    reason: string;
}
export type EmployeeKey = string;
export interface Notification {
    id: string;
    title: string;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: bigint;
    isRead: boolean;
    message: string;
    relatedId?: string;
}
export interface Branch {
    id: string;
    name: string;
    isActive: boolean;
    location: string;
}
export interface Employee {
    id: EmployeeKey;
    salary: number;
    userId: Principal;
    name: string;
    designation: string;
    role: string;
    joiningDate: string;
    isActive: boolean;
    email: string;
    employeeId: string;
    phone: string;
    photo?: ExternalBlob;
    department: string;
    branchId: string;
    shiftId: string;
}
export interface AttendanceRecord {
    id: string;
    locationLat?: number;
    locationLng?: number;
    status: AttendanceStatus;
    date: string;
    checkInTime?: bigint;
    employeeId: string;
    notes: string;
    checkOutTime?: bigint;
    overtimeMinutes: bigint;
}
export interface Holiday {
    id: string;
    holidayType: string;
    isRecurring: boolean;
    date: string;
    name: string;
}
export interface LeaveBalance {
    paid: number;
    sick: number;
    year: bigint;
    unpaid: number;
    employeeId: string;
    casual: number;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum AttendanceStatus {
    halfDay = "halfDay",
    present = "present",
    late = "late",
    absent = "absent",
    holiday = "holiday"
}
export enum LeaveStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum LeaveType {
    paid = "paid",
    sick = "sick",
    unpaid = "unpaid",
    casual = "casual"
}
export enum NotificationType {
    leaveApproved = "leaveApproved",
    leaveRejected = "leaveRejected",
    lateAlert = "lateAlert",
    general = "general"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addShift(shift: Shift): Promise<void>;
    applyLeave(request: LeaveRequest): Promise<string>;
    approveLeave(leaveId: string, reviewNote: string | null): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    checkIn(locationLat: number | null, locationLng: number | null, notes: string): Promise<string>;
    checkOut(recordId: string): Promise<void>;
    createBranch(branch: Branch): Promise<void>;
    createEmployee(employee: Employee): Promise<void>;
    createHoliday(holiday: Holiday): Promise<void>;
    deleteEmployee(id: EmployeeKey): Promise<void>;
    deleteHoliday(id: string): Promise<void>;
    getAllEmployees(): Promise<Array<Employee>>;
    getBranch(id: string): Promise<Branch>;
    getBranches(): Promise<Array<Branch>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardStats(): Promise<{
        totalWorkingHoursThisMonth: number;
        totalEmployees: bigint;
        presentToday: bigint;
        lateToday: bigint;
        pendingLeaves: bigint;
        absentToday: bigint;
        avgWorkingHoursPerEmployee: number;
    }>;
    getEmployee(id: EmployeeKey): Promise<Employee>;
    getHoliday(id: string): Promise<Holiday>;
    getHolidays(): Promise<Array<Holiday>>;
    getLeaveBalance(employeeId: string): Promise<LeaveBalance | null>;
    getMyAttendance(month: string): Promise<Array<AttendanceRecord>>;
    getMyLeaves(): Promise<Array<LeaveRequest>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyProfile(): Promise<Employee | null>;
    getPayrollSummary(employeeId: string, month: string, _year: bigint): Promise<{
        salary: number;
        estimatedEarnings: number;
        daysPresent: bigint;
        workingDays: bigint;
        overtimeHours: number;
    }>;
    getPendingLeaves(): Promise<Array<LeaveRequest>>;
    getShift(id: string): Promise<Shift>;
    getShifts(): Promise<Array<Shift>>;
    getTeamAttendance(_date: string): Promise<Array<AttendanceRecord>>;
    getTodayStats(): Promise<{
        present: bigint;
        late: bigint;
        absent: bigint;
    }>;
    getUnreadCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initLeaveBalance(balance: LeaveBalance): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markAbsent(_date: string): Promise<void>;
    markAllRead(): Promise<void>;
    markNotificationRead(notifId: string): Promise<void>;
    rejectLeave(leaveId: string, reviewNote: string | null): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchEmployees(searchText: string, searchBy: string): Promise<Array<Employee>>;
    updateBranch(id: string, branch: Branch): Promise<void>;
    updateEmployee(id: EmployeeKey, updates: Employee): Promise<void>;
    updateShift(id: string, shift: Shift): Promise<void>;
}
import type { AttendanceRecord as _AttendanceRecord, AttendanceStatus as _AttendanceStatus, Employee as _Employee, EmployeeKey as _EmployeeKey, ExternalBlob as _ExternalBlob, LeaveBalance as _LeaveBalance, LeaveRequest as _LeaveRequest, LeaveStatus as _LeaveStatus, LeaveType as _LeaveType, Notification as _Notification, NotificationType as _NotificationType, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addShift(arg0: Shift): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShift(arg0);
            return result;
        }
    }
    async applyLeave(arg0: LeaveRequest): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.applyLeave(to_candid_LeaveRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyLeave(to_candid_LeaveRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveLeave(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLeave(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLeave(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n15(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkIn(arg0: number | null, arg1: number | null, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.checkIn(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkIn(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n17(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async checkOut(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOut(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOut(arg0);
            return result;
        }
    }
    async createBranch(arg0: Branch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBranch(arg0);
            return result;
        }
    }
    async createEmployee(arg0: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmployee(await to_candid_Employee_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmployee(await to_candid_Employee_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createHoliday(arg0: Holiday): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHoliday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHoliday(arg0);
            return result;
        }
    }
    async deleteEmployee(arg0: EmployeeKey): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEmployee(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEmployee(arg0);
            return result;
        }
    }
    async deleteHoliday(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteHoliday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteHoliday(arg0);
            return result;
        }
    }
    async getAllEmployees(): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployees();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployees();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBranch(arg0: string): Promise<Branch> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranch(arg0);
            return result;
        }
    }
    async getBranches(): Promise<Array<Branch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBranches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBranches();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<{
        totalWorkingHoursThisMonth: number;
        totalEmployees: bigint;
        presentToday: bigint;
        lateToday: bigint;
        pendingLeaves: bigint;
        absentToday: bigint;
        avgWorkingHoursPerEmployee: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getEmployee(arg0: EmployeeKey): Promise<Employee> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployee(arg0);
                return from_candid_Employee_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployee(arg0);
            return from_candid_Employee_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHoliday(arg0: string): Promise<Holiday> {
        if (this.processError) {
            try {
                const result = await this.actor.getHoliday(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHoliday(arg0);
            return result;
        }
    }
    async getHolidays(): Promise<Array<Holiday>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHolidays();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHolidays();
            return result;
        }
    }
    async getLeaveBalance(arg0: string): Promise<LeaveBalance | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaveBalance(arg0);
                return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaveBalance(arg0);
            return from_candid_opt_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyAttendance(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyAttendance(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyAttendance(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLeaves(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLeaves();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLeaves();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<Employee | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPayrollSummary(arg0: string, arg1: string, arg2: bigint): Promise<{
        salary: number;
        estimatedEarnings: number;
        daysPresent: bigint;
        workingDays: bigint;
        overtimeHours: number;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPayrollSummary(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPayrollSummary(arg0, arg1, arg2);
            return result;
        }
    }
    async getPendingLeaves(): Promise<Array<LeaveRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingLeaves();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingLeaves();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShift(arg0: string): Promise<Shift> {
        if (this.processError) {
            try {
                const result = await this.actor.getShift(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShift(arg0);
            return result;
        }
    }
    async getShifts(): Promise<Array<Shift>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShifts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShifts();
            return result;
        }
    }
    async getTeamAttendance(arg0: string): Promise<Array<AttendanceRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeamAttendance(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeamAttendance(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTodayStats(): Promise<{
        present: bigint;
        late: bigint;
        absent: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTodayStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTodayStats();
            return result;
        }
    }
    async getUnreadCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async initLeaveBalance(arg0: LeaveBalance): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initLeaveBalance(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initLeaveBalance(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAbsent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAbsent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAbsent(arg0);
            return result;
        }
    }
    async markAllRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllRead();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async rejectLeave(arg0: string, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectLeave(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectLeave(arg0, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchEmployees(arg0: string, arg1: string): Promise<Array<Employee>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEmployees(arg0, arg1);
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEmployees(arg0, arg1);
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBranch(arg0: string, arg1: Branch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBranch(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBranch(arg0, arg1);
            return result;
        }
    }
    async updateEmployee(arg0: EmployeeKey, arg1: Employee): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmployee(arg0, await to_candid_Employee_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmployee(arg0, await to_candid_Employee_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateShift(arg0: string, arg1: Shift): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShift(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShift(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_AttendanceStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceStatus): AttendanceStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Employee_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Employee): Promise<Employee> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LeaveRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveRequest): LeaveRequest {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveStatus): LeaveStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_LeaveType_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeaveType): LeaveType {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationType): NotificationType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n25(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_LeaveBalance]): LeaveBalance | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Employee]): Promise<Employee | null> {
    return value.length === 0 ? null : await from_candid_Employee_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EmployeeKey;
    salary: number;
    userId: Principal;
    name: string;
    designation: string;
    role: string;
    joiningDate: string;
    isActive: boolean;
    email: string;
    employeeId: string;
    phone: string;
    photo: [] | [_ExternalBlob];
    department: string;
    branchId: string;
    shiftId: string;
}): Promise<{
    id: EmployeeKey;
    salary: number;
    userId: Principal;
    name: string;
    designation: string;
    role: string;
    joiningDate: string;
    isActive: boolean;
    email: string;
    employeeId: string;
    phone: string;
    photo?: ExternalBlob;
    department: string;
    branchId: string;
    shiftId: string;
}> {
    return {
        id: value.id,
        salary: value.salary,
        userId: value.userId,
        name: value.name,
        designation: value.designation,
        role: value.role,
        joiningDate: value.joiningDate,
        isActive: value.isActive,
        email: value.email,
        employeeId: value.employeeId,
        phone: value.phone,
        photo: record_opt_to_undefined(await from_candid_opt_n24(_uploadFile, _downloadFile, value.photo)),
        department: value.department,
        branchId: value.branchId,
        shiftId: value.shiftId
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    locationLat: [] | [number];
    locationLng: [] | [number];
    status: _AttendanceStatus;
    date: string;
    checkInTime: [] | [bigint];
    employeeId: string;
    notes: string;
    checkOutTime: [] | [bigint];
    overtimeMinutes: bigint;
}): {
    id: string;
    locationLat?: number;
    locationLng?: number;
    status: AttendanceStatus;
    date: string;
    checkInTime?: bigint;
    employeeId: string;
    notes: string;
    checkOutTime?: bigint;
    overtimeMinutes: bigint;
} {
    return {
        id: value.id,
        locationLat: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.locationLat)),
        locationLng: record_opt_to_undefined(from_candid_opt_n33(_uploadFile, _downloadFile, value.locationLng)),
        status: from_candid_AttendanceStatus_n34(_uploadFile, _downloadFile, value.status),
        date: value.date,
        checkInTime: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.checkInTime)),
        employeeId: value.employeeId,
        notes: value.notes,
        checkOutTime: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.checkOutTime)),
        overtimeMinutes: value.overtimeMinutes
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _LeaveStatus;
    appliedAt: bigint;
    endDate: string;
    days: number;
    reviewNote: [] | [string];
    reviewedAt: [] | [bigint];
    reviewedBy: [] | [string];
    employeeId: string;
    leaveType: _LeaveType;
    startDate: string;
    reason: string;
}): {
    id: string;
    status: LeaveStatus;
    appliedAt: bigint;
    endDate: string;
    days: number;
    reviewNote?: string;
    reviewedAt?: bigint;
    reviewedBy?: string;
    employeeId: string;
    leaveType: LeaveType;
    startDate: string;
    reason: string;
} {
    return {
        id: value.id,
        status: from_candid_LeaveStatus_n40(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        endDate: value.endDate,
        days: value.days,
        reviewNote: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.reviewNote)),
        reviewedAt: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.reviewedAt)),
        reviewedBy: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.reviewedBy)),
        employeeId: value.employeeId,
        leaveType: from_candid_LeaveType_n43(_uploadFile, _downloadFile, value.leaveType),
        startDate: value.startDate,
        reason: value.reason
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    userId: Principal;
    notificationType: _NotificationType;
    createdAt: bigint;
    isRead: boolean;
    message: string;
    relatedId: [] | [string];
}): {
    id: string;
    title: string;
    userId: Principal;
    notificationType: NotificationType;
    createdAt: bigint;
    isRead: boolean;
    message: string;
    relatedId?: string;
} {
    return {
        id: value.id,
        title: value.title,
        userId: value.userId,
        notificationType: from_candid_NotificationType_n48(_uploadFile, _downloadFile, value.notificationType),
        createdAt: value.createdAt,
        isRead: value.isRead,
        message: value.message,
        relatedId: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.relatedId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    halfDay: null;
} | {
    present: null;
} | {
    late: null;
} | {
    absent: null;
} | {
    holiday: null;
}): AttendanceStatus {
    return "halfDay" in value ? AttendanceStatus.halfDay : "present" in value ? AttendanceStatus.present : "late" in value ? AttendanceStatus.late : "absent" in value ? AttendanceStatus.absent : "holiday" in value ? AttendanceStatus.holiday : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): LeaveStatus {
    return "pending" in value ? LeaveStatus.pending : "approved" in value ? LeaveStatus.approved : "rejected" in value ? LeaveStatus.rejected : value;
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    paid: null;
} | {
    sick: null;
} | {
    unpaid: null;
} | {
    casual: null;
}): LeaveType {
    return "paid" in value ? LeaveType.paid : "sick" in value ? LeaveType.sick : "unpaid" in value ? LeaveType.unpaid : "casual" in value ? LeaveType.casual : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    leaveApproved: null;
} | {
    leaveRejected: null;
} | {
    lateAlert: null;
} | {
    general: null;
}): NotificationType {
    return "leaveApproved" in value ? NotificationType.leaveApproved : "leaveRejected" in value ? NotificationType.leaveRejected : "lateAlert" in value ? NotificationType.lateAlert : "general" in value ? NotificationType.general : value;
}
async function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Employee>): Promise<Array<Employee>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Employee_n22(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LeaveRequest>): Array<LeaveRequest> {
    return value.map((x)=>from_candid_LeaveRequest_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n46(_uploadFile, _downloadFile, x));
}
async function to_candid_Employee_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Employee): Promise<_Employee> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_LeaveRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveRequest): _LeaveRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): _LeaveStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_LeaveType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): _LeaveType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EmployeeKey;
    salary: number;
    userId: Principal;
    name: string;
    designation: string;
    role: string;
    joiningDate: string;
    isActive: boolean;
    email: string;
    employeeId: string;
    phone: string;
    photo?: ExternalBlob;
    department: string;
    branchId: string;
    shiftId: string;
}): Promise<{
    id: _EmployeeKey;
    salary: number;
    userId: Principal;
    name: string;
    designation: string;
    role: string;
    joiningDate: string;
    isActive: boolean;
    email: string;
    employeeId: string;
    phone: string;
    photo: [] | [_ExternalBlob];
    department: string;
    branchId: string;
    shiftId: string;
}> {
    return {
        id: value.id,
        salary: value.salary,
        userId: value.userId,
        name: value.name,
        designation: value.designation,
        role: value.role,
        joiningDate: value.joiningDate,
        isActive: value.isActive,
        email: value.email,
        employeeId: value.employeeId,
        phone: value.phone,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        department: value.department,
        branchId: value.branchId,
        shiftId: value.shiftId
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: LeaveStatus;
    appliedAt: bigint;
    endDate: string;
    days: number;
    reviewNote?: string;
    reviewedAt?: bigint;
    reviewedBy?: string;
    employeeId: string;
    leaveType: LeaveType;
    startDate: string;
    reason: string;
}): {
    id: string;
    status: _LeaveStatus;
    appliedAt: bigint;
    endDate: string;
    days: number;
    reviewNote: [] | [string];
    reviewedAt: [] | [bigint];
    reviewedBy: [] | [string];
    employeeId: string;
    leaveType: _LeaveType;
    startDate: string;
    reason: string;
} {
    return {
        id: value.id,
        status: to_candid_LeaveStatus_n10(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        endDate: value.endDate,
        days: value.days,
        reviewNote: value.reviewNote ? candid_some(value.reviewNote) : candid_none(),
        reviewedAt: value.reviewedAt ? candid_some(value.reviewedAt) : candid_none(),
        reviewedBy: value.reviewedBy ? candid_some(value.reviewedBy) : candid_none(),
        employeeId: value.employeeId,
        leaveType: to_candid_LeaveType_n12(_uploadFile, _downloadFile, value.leaveType),
        startDate: value.startDate,
        reason: value.reason
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == LeaveStatus.pending ? {
        pending: null
    } : value == LeaveStatus.approved ? {
        approved: null
    } : value == LeaveStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeaveType): {
    paid: null;
} | {
    sick: null;
} | {
    unpaid: null;
} | {
    casual: null;
} {
    return value == LeaveType.paid ? {
        paid: null
    } : value == LeaveType.sick ? {
        sick: null
    } : value == LeaveType.unpaid ? {
        unpaid: null
    } : value == LeaveType.casual ? {
        casual: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
